import 'package:shopping_cart/model/product.dart';

List<Product> products = [
  Product(name: "SmartWatch Pro", category: Category.tech, price: 199.99),
  Product(name: "Yoga Mat", category: Category.lifestyle, price: 29.99),
  Product(name: "Bluetooth Earbuds", category: Category.tech, price: 79.99),
  Product(name: "Organic Herbal Tea Set", category: Category.lifestyle, price: 14.99),
  Product(name: "Fitness Tracker Band", category: Category.sport, price: 49.99),
  Product(name: "Smartphone Charging Dock", category: Category.tech, price: 34.99),
  Product(name: "Aromatherapy Essential Oil Diffuser", category: Category.lifestyle, price: 24.99),
  Product(name: "High-Performance Running Shoes", category: Category.sport, price: 129.99),
  Product(name: "Virtual Reality Headset", category: Category.tech, price: 299.99),
  Product(name: "Organic Cotton Bed Sheets", category: Category.lifestyle, price: 59.99),
  Product(name: "Protein Powder", category: Category.sport, price: 39.99),
  Product(name: "Smart Home Security Camera", category: Category.tech, price: 149.99),
  Product(name: "Journaling Set", category: Category.lifestyle, price: 19.99),
  Product(name: "Resistance Bands Set", category: Category.sport, price: 24.99),
  Product(name: "Wireless Charging Pad", category: Category.tech, price: 39.99),
  Product(name: "Indoor Plant Kit", category: Category.lifestyle, price: 39.99),
  Product(name: "Golf Club Set", category: Category.sport, price: 299.99),
  Product(name: "Noise-Canceling Headphones", category: Category.tech, price: 249.99),
  Product(name: "Portable Blender", category: Category.lifestyle, price: 49.99),
  Product(name: "Yoga Block Set", category: Category.sport, price: 19.99),
  Product(name: "Smart Thermostat", category: Category.tech, price: 129.99),
  Product(name: "Recipe Book Stand", category: Category.lifestyle, price: 14.99),
  Product(name: "Trail Running Backpack", category: Category.sport, price: 69.99),
  Product(name: "Solar-Powered Outdoor Lights", category: Category.tech, price: 44.99),
  Product(name: "Meditation Cushion", category: Category.lifestyle, price: 34.99),
];